from fpdf import FPDF
import os

def create_pdf_ticket(pnr, source, dest, date, passengers, amount):
    # Determine base directory of this script
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    
    # Ensure directory exists locally
    local_ticket_dir = os.path.join(BASE_DIR, 'static', 'tickets')
    if not os.path.exists(local_ticket_dir) and not os.environ.get('VERCEL'):
        os.makedirs(local_ticket_dir)
        
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(0, 74, 173) # Primary Blue
    pdf.cell(200, 20, txt="ADHI BUS TRAVELS", ln=True, align='C')
    
    pdf.set_font("Arial", 'I', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(200, 10, txt="Safe and Happy Journey Across Tamil Nadu", ln=True, align='C')
    pdf.ln(10)
    
    # Trip Info
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(200, 10, txt=f"E-TICKET: {pnr}", ln=True, align='L')
    pdf.ln(5)
    
    # Table like structure
    pdf.set_font("Arial", '', 12)
    pdf.cell(95, 10, txt=f"Source: {source}", border=1)
    pdf.cell(95, 10, txt=f"Destination: {dest}", border=1, ln=True)
    
    pdf.cell(95, 10, txt=f"Travel Date: {date}", border=1)
    pdf.cell(95, 10, txt=f"Passengers: {passengers}", border=1, ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(190, 10, txt=f"Total Amount Paid: Rs. {amount}", border=1, ln=True)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, txt="Instructions:\n1. Please report at the boarding point 15 mins before departure.\n2. Carry a valid Photo ID proof.\n3. This is an e-ticket, no need to print.")
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Adhii Chatbot - Official Bus Partner of TN", align='C')
    
    file_path = os.path.join(local_ticket_dir, f"ticket_{pnr}.pdf")
    pdf.output(file_path)
    return f"/download_ticket/{pnr}"

if __name__ == "__main__":
    create_pdf_ticket("TEST123", "Chennai", "Madurai", "20/05/2026", "2", 1300.0)
    print("Test ticket generated.")
